rec-2Parcial/Practica-segundoParcial/ObrasDeArte/Models/ErrorViewModel.cs
using System;

namespace ObrasDeArte.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

rec-2Parcial/Practica-segundoParcial/ObrasDeArte/Controllers/ObrasDeArteController.cs
using BD.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ObrasDeArte.Models;
using ObrasDeArte.Service;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ObrasDeArte.Controllers
{
    public class ObrasDeArteController : Controller
    {
        private readonly ILogger<ObrasDeArteController> _logger;
        private IObraDeArteService ObraDeArteService;

        public ObrasDeArteController(ILogger<ObrasDeArteController> logger,IObraDeArteService obraDeArteService)
        {
            this.ObraDeArteService = obraDeArteService;
            _logger = logger;
        }

        public ActionResult Index()
        {
            List<ObraDeArte> obrasDeArte = ObraDeArteService.ListarObras();
            return View(obrasDeArte);
        }

        public ActionResult Agregar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Agregar(ObraDeArte obraDeArte)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                ObraDeArteService.AgregarObra(obraDeArte);
                return View("Index",ObraDeArteService.ListarObras());
            }
        }

        public ActionResult SigloXIX()
        {
            return View(ObraDeArteService.ObrasDeArteSigloXIX());
        }

        public ActionResult Eliminar(int Id)
        {
            ObraDeArteService.Eliminar(Id);
            return View("Index",ObraDeArteService.ListarObras());
        }

        public ActionResult Editar(int Id)
        {
            return View(ObraDeArteService.buscarPorId(Id));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

rec-2Parcial/Practica-segundoParcial/ObrasDeArte/Views/ObrasDeArte/Agregar.cshtml
<form method="post" action="/ObrasDeArte/Agregar">
    <div>
        Nombre de la obra: 
        <input type="text" name="Nombre"/>
    </div>
    <div>
        Año de Creación
        <input type="number" name="AnioCreacion"/>
    </div>
    <div>
        <input type="submit" value="Grabar"/>
    </div>
</form>

rec-2Parcial/Practica-segundoParcial/ObrasDeArte/Views/ObrasDeArte/Editar.cshtml
@model BD.DB.ObraDeArte

<form method="post" action="/ObrasDeArte/Editar">
    <div>
        Nombre de la obra: 
        <input type="text" name="Nombre" value="@Model.Nombre"/>
    </div>
    <div>
        Año de Creación
        <input type="number" name="AnioCreacion" value="@Model.AnioCreacion"/>
    </div>
    <div>
        <input type="submit" value="Modificar"/>
    </div>
</form>

rec-2Parcial/Practica-segundoParcial/ObrasDeArte/Views/ObrasDeArte/Index.cshtml
@model List<BD.DB.ObraDeArte>

<a href="ObrasDeArte/Agregar" class="btn btn-success">Agregar</a>
<a href="ObrasDeArte/SigloXIX" class="btn btn-success">ObrasDelSigloXIX</a>

<table>
        <tr>
            <th>Nombre</th>
            <th>Año de Creación</th>
            <th>Eliminar</th>
        </tr>
        @foreach (var obraDeArte in Model)
        {
            <tr>
                <td>@obraDeArte.Nombre</td>
                <td>@obraDeArte.AnioCreacion</td>
                <td>@Html.ActionLink("Eliminar", "Eliminar", new { Id = obraDeArte.Id },
                                       new { @class = "btnagre", @name = "Eliminar" })</td>
            </tr>
        }
</table>

rec-2Parcial/Practica-segundoParcial/ObrasDeArte/Views/ObrasDeArte/SigloXIX.cshtml
@model List<BD.DB.ObraDeArte>

<a href="/ObrasDeArte/Index" class="btn btn-primary">Volver</a>

<table>
        <tr>
            <th>Nombre</th>
            <th>Año de Creación</th>
        </tr>
        @foreach (var obraDeArte in Model)
        {
            <tr>
                <td>@obraDeArte.Nombre</td>
                <td>@obraDeArte.AnioCreacion</td>
            </tr>
        }
</table>

rec-2Parcial/Practica-segundoParcial/ObrasDeArte/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ObrasDeArte</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ObrasDeArte</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ObrasDeArte" asp-action="Index">Lista</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ObrasDeArte" asp-action="SigloXIX">SigloXIX</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ObrasDeArte - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>