practica-futbol/futbol/futbol/Models/ErrorViewModel.cs
using System;

namespace futbol.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

practica-futbol/futbol/futbol/Controllers/FutbolController.cs
using futbol.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Servicio.DB;
using Servicio.Service;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace futbol.Controllers
{
    public class FutbolController : Controller
    {
        private IJugadorService _JugadorService;
        private IEquipoService _EquipoService;

        public FutbolController(IJugadorService jugadorService,IEquipoService equipoService)
        {
           this._JugadorService =  jugadorService;
            this._EquipoService = equipoService;
        }

        public IActionResult Index()
        {
            ViewBag.equipos = _EquipoService.listarEquipos();
            return View(_JugadorService.ObtenerTodos());
        }

        [HttpPost]
        public IActionResult Filtrar(int? IdEquipo)
        {
            ViewBag.equipos = _EquipoService.listarEquipos();
            if (IdEquipo.HasValue)
            {
                return View("Index",_JugadorService.ObtenerJugadoresPorEquipo(IdEquipo.Value));
            }
            return View("Index",_JugadorService.ObtenerTodos());
        }

        public ActionResult Agregar()
        {
            ViewBag.equipos = _EquipoService.listarEquipos();
            return View();
        }
        [HttpPost]
        public ActionResult Agregar(Jugador jugador)
        {
            if (ModelState.IsValid)
            {
                _JugadorService.Agregar(jugador);
                ViewBag.equipos = _EquipoService.listarEquipos();
                return View("Index",_JugadorService.ObtenerTodos());
            }
            return View();
        }

        public ActionResult Eliminar (int IdJugador)
        {
            _JugadorService.Eliminar(IdJugador);
            ViewBag.equipos = _EquipoService.listarEquipos();
            return View("Index", _JugadorService.ObtenerTodos());
        }

    }
}

practica-futbol/futbol/futbol/Views/Futbol/Agregar.cshtml
@model List<Servicio.DB.Jugador>

<form action="/Futbol/Agregar" method="post">
    <div>
        Nombre:
        <input type="text" name="Nombre" />
    </div>
    <div>
        Apellido:
        <input type="text" name="Apellido" />
    </div>
    <div>
        Peso:
        <input type="number" name="Peso" />
    </div>
    <div>
        Edad:
        <input type="number" name="Edad" />
    </div>
    <div>
         
        Equipo:
        <select name="IdEquipo">
            <option value="">Equipo</option>
            @foreach (var equipo in ViewBag.equipos)
            {
                <option value="@equipo.IdEquipo">@equipo.Nombre</option>
            }
        </select>
    </div>
    <div>
        <input type="submit" value="Guardar" />
    </div>
</form>

practica-futbol/futbol/futbol/Views/Futbol/Index.cshtml
@model List<Servicio.DB.Jugador>
<form action="/Futbol/Filtrar" method="post">

    <div>
         
        Equipo:
        <select name="IdEquipo">
            <option value="">Equipo</option>
            @foreach (var equipo in ViewBag.equipos)
            {
                <option value="@equipo.IdEquipo">@equipo.Nombre</option>
            }
        </select>
    </div>
    <input type="submit" name="Filtrar" value="Filtrar" />
    <table>
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Edad</th>
            <th>Peso</th>
            <th>Equipo</th>
            <th>Eliminar</th>
        </tr>
        @foreach (var jugador in Model)
        {
            <tr>
                <td>@jugador.Nombre</td>
                <td>@jugador.Apellido</td>
                <td>@jugador.Edad</td>
                <td>@jugador.Peso</td>
                <td>@jugador.IdEquipoNavigation.Nombre</td>
                <td>@Html.ActionLink("Eliminar", "Eliminar", new { IdJugador = jugador.IdJugador },
                                       new { @class = "btnagre", @name = "Eliminar" })</td>
            </tr>
        }
    </table>
</form>

practica-futbol/futbol/futbol/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - futbol</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">futbol</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Futbol" asp-action="Agregar">Agregar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - futbol - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>