src/ClasificadorAnimales.Web/Models/ErrorViewModel.cs
using System;

namespace ClasificadorAnimales.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/ClasificadorAnimales.Web/Controllers/AnimalController.cs
using ClasificadorAnimales.Data.EF;
using ClasificadorAnimales.Servicio.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ClasificadorAnimales.Web.Controllers
{
    public class AnimalController : Controller
    {
        ITipoAnimalService _tipoAnimalService;
        IAnimalServices _animalServices;

        public AnimalController(ITipoAnimalService tipoAnimalService, IAnimalServices animalServices)
        {
            _tipoAnimalService = tipoAnimalService;
            _animalServices = animalServices;
        }

        // GET: AnimalController
        public ActionResult Alta()
        {
            ViewBag.TipoAnimal = _tipoAnimalService.ObtenerTodos();
            return View();
        }

        [HttpPost]
        public ActionResult Alta(Animal animal)
        {
            if (!ModelState.IsValid && string.IsNullOrEmpty(Request.Form["OtroTipo"]))
            {
                List<TipoAnimal> tipoAnimales = _tipoAnimalService.ObtenerTodos();
                ViewBag.TipoAnimales = tipoAnimales;
                return View(animal);
            }
            _animalServices.Insertar(animal);
            return RedirectToAction("Index");
        }

        public ActionResult ListarAnimales()
        {
            ViewBag.TipoAnimales = _tipoAnimalService.ObtenerTodos();
            return View(_animalServices.ObtenerTodos());
        }

        [HttpPost]
        public ActionResult ListarAnimales(int? IdTipoAnimal)
        {
            ViewBag.TipoAnimales = _tipoAnimalService.ObtenerTodos();
            if (IdTipoAnimal.HasValue)
            {
                return View(_animalServices.ObtenerPorTipo(IdTipoAnimal.Value));
            }
            return View(_animalServices.ObtenerTodos());
        }

        public ActionResult Eliminar(int IdTipoAnimal)
        {
            _animalServices.Eliminar(IdTipoAnimal);
            return RedirectToAction("ListarAnimales");
        }

        public ActionResult Modificar(int IdAnimal)
        {
            ViewBag.TipoAnimal = _tipoAnimalService.ObtenerTodos();
            Animal animal = _animalServices.AnimalPorId(IdAnimal);
            return View("ModificarAnimal",animal);
        }

        [HttpPost]
        public ActionResult Modificar(Animal animal)
        {
            if (!ModelState.IsValid)
            {
                return View("ModificarAnimal", animal);
            }
            _animalServices.ModificarAnimal(animal);
            return RedirectToAction("ListarAnimales");
        }
    }
}

src/ClasificadorAnimales.Web/Controllers/HomeController.cs
using ClasificadorAnimales.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ClasificadorAnimales.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/ClasificadorAnimales.Web/Views/Animal/Alta.cshtml
@model ClasificadorAnimales.Data.EF.Animal

   
    <form action="/Animal/Alta" method="post">
        <div>
            Nombre:
            <input type="text" name="NombreEspecie" />
        </div>
        <div>
            Peso:
            <input type="number" name="PesoPromedio" />
        </div>
        <div>
            Edad:
            <input type="number" name="EdadPromedio" />
        </div>
        <div>
            Tipo Animal :
            <select name="IdTipoAnimal">
                <option value="">TipoAnimal</option>
            @foreach(var tipoAnimal in (List<ClasificadorAnimales.Data.EF.TipoAnimal>) ViewBag.TipoAnimal)
            {
                <option value="@tipoAnimal.IdTipoAnimal">@tipoAnimal.Nombre</option>
            }
        </select>
        </div>
        <div>
            <input type="submit" value="Guardar"/>
        </div>
    </form>
   

src/ClasificadorAnimales.Web/Views/Animal/ListarAnimales.cshtml
@model List<ClasificadorAnimales.Data.EF.Animal>
<form action="/Animal/ListarAnimales" method="post">
    <partial name="_pvTipoAnimal.cshtml" model="@ViewBag.TipoAnimales" />
    <input type="submit" name="Filtrar" value="Filtrar" />
    <table>
        <tr>
            <th>Nombre</th>
            <th>Peso</th>
            <th>Edad</th>
            <th>Tipo</th>
            <th>Eliminar</th>
            <th>Editar</th>
        </tr>
        @foreach (var animal in Model)
        {
            <tr>
                <td>@animal.NombreEspecie</td>
                <td>@animal.PesoPromedio</td>
                <td>@animal.EdadPromedio</td>
                <td>@animal.IdTipoAnimalNavigation.Nombre</td>
                <td>@Html.ActionLink("Eliminar", "Eliminar", new { IdTipoAnimal = animal.IdAnimal },
                                       new { @class = "btnagre", @name = "Eliminar" })</td>
                <td>@Html.ActionLink("Modificar", "Modificar", new { IdAnimal = animal.IdAnimal },
                                       new { @class = "btnagre", @name = "Eliminar" })</td>
            </tr>

        }
    </table>

</form>

src/ClasificadorAnimales.Web/Views/Animal/ModificarAnimal.cshtml
@model ClasificadorAnimales.Data.EF.Animal

   
    <form action="/Animal/Modificar" method="post">
        <div>
            <input type="hidden" asp-for="IdAnimal" />
        </div>
        <div>
            Nombre:
            <input type="text" name="NombreEspecie" value=@Model.NombreEspecie />
        </div>
        <div>
            Peso:
            <input type="number" name="PesoPromedio" value=@Model.PesoPromedio />
        </div>
        <div>
            Edad:
            <input type="number" name="EdadPromedio" value=@Model.EdadPromedio />
        </div>
        <div>
            Tipo Animal :
            <select name="IdTipoAnimal">
                <option value="">TipoAnimal</option>
            @foreach(var tipoAnimal in (List<ClasificadorAnimales.Data.EF.TipoAnimal>) ViewBag.TipoAnimal)
            {
                <option value="@tipoAnimal.IdTipoAnimal">@tipoAnimal.Nombre</option>
            }
        </select>
        </div>
        <div>
            <input type="submit" value="Modificar"/>
        </div>
    </form>

src/ClasificadorAnimales.Web/Views/Animal/_pvTipoAnimal.cshtml
@model List<ClasificadorAnimales.Data.EF.TipoAnimal>
<div>
    Tipo Animal:
    <select name="IdTipoAnimal">
        <option value="">Tipo Animal</option>
        @foreach (var tipoAnimal in Model)
        {
            <option value="@tipoAnimal.IdTipoAnimal">@tipoAnimal.Nombre</option>
        }
    </select>
</div>

src/ClasificadorAnimales.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/ClasificadorAnimales.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClasificadorAnimales.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClasificadorAnimales.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="Alta">Alta Animal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="ListarAnimales">Listar Animal</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ClasificadorAnimales.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>